quarkus.liquibase.change-log=classpath:liquibase/master.xml
quarkus.liquibase.migrate-at-start=true

%dev.quarkus.hibernate-search-orm.elasticsearch.hosts=localhost:9200
%dev.quarkus.hibernate-search-orm.elasticsearch.version=8.13.4
%dev.quarkus.hibernate-search-orm.schema-management.strategy=drop-and-create

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/repository
%dev.quarkus.datasource.username=repository
%dev.quarkus.datasource.password=12345

%dev.quarkus.datasource.dev-ui.allow-sql=true

quarkus.http.virtual=true

quarkus.smallrye-openapi.open-api-version=3.0.3
